package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"github.com/nchgroup/tcpsh/internal/client"
	"github.com/nchgroup/tcpsh/internal/config"
	"github.com/nchgroup/tcpsh/internal/console"
	"github.com/nchgroup/tcpsh/internal/server"

	"github.com/spf13/cobra"
)

var (
	flagQuiet  bool
	flagPort   int
	flagServer string
	flagClient string
	flagToken  string
)

var rootCmd = &cobra.Command{
	Use:   "tcpsh",
	Short: "Interactive TCP connection manager",
	Long: `tcpsh — an interactive TCP server and connection manager.

Modes:
  Console (default)   Interactive REPL on the local terminal.
  Server  (--server)  Headless daemon; a client connects over encrypted TCP.
  Client  (--client)  Connects to a running tcpsh server.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load()
		if err != nil {
			return fmt.Errorf("config: %w", err)
		}
		if flagQuiet {
			cfg.Quiet = true
		}

		switch {
		case flagServer != "":
			srv, err := server.New(cfg, flagServer, resolveServerToken(flagToken))
			if err != nil {
				return err
			}
			return srv.Run()

		case flagClient != "":
			token := resolveToken(flagToken)
			if token == "" {
				return fmt.Errorf("no token provided — use --token or set TCPSH_TOKEN")
			}
			return client.New(flagClient, token).Run()

		default:
			// Console mode (original behaviour).
			repl, err := console.New(cfg)
			if err != nil {
				return err
			}
			if flagPort > 0 {
				fmt.Printf("Opening port %d...\n", flagPort)
			}
			return repl.Run()
		}
	},
}

// Execute runs the root command.
func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func init() {
	rootCmd.PersistentFlags().BoolVarP(&flagQuiet, "quiet", "q", false, "Suppress banner and notifications")
	rootCmd.PersistentFlags().IntVarP(&flagPort, "port", "p", 0, "Open a port immediately on startup (console mode)")
	rootCmd.PersistentFlags().StringVarP(&flagServer, "server", "s", "", "Start in server mode, listening on <bind:port>")
	rootCmd.PersistentFlags().StringVarP(&flagClient, "client", "c", "", "Connect as client to a tcpsh server at <host:port>")
	rootCmd.PersistentFlags().StringVar(&flagToken, "token", "", "Token for --server (hardcode) or --client (authenticate); overrides TCPSH_TOKEN env")
}

// resolveServerToken returns the token for --server mode.
// Priority: --token flag → TCPSH_TOKEN env → empty (random token generated by server).
func resolveServerToken(flagValue string) string {
	if flagValue != "" {
		return flagValue
	}
	return os.Getenv("TCPSH_TOKEN")
}

// resolveToken returns the token to use for --client mode.
// Priority: --token flag → TCPSH_TOKEN env → interactive prompt.
func resolveToken(flagValue string) string {
	if flagValue != "" {
		return flagValue
	}
	if t := os.Getenv("TCPSH_TOKEN"); t != "" {
		return t
	}
	// Interactive prompt as last resort.
	fmt.Print("Token: ")
	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}
