package cmd

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/nchgroup/tcpsh/internal/client"
	"github.com/nchgroup/tcpsh/internal/config"
	"github.com/nchgroup/tcpsh/internal/console"
	"github.com/nchgroup/tcpsh/internal/server"
)

var (
	flagQuiet  = flag.Bool("quiet", false, "Suppress banner and notifications")
	flagPort   = flag.Int("port", 0, "Open a port immediately on startup (console mode)")
	flagServer = flag.String("server", "", "Start in server mode, listening on <bind:port>")
	flagClient = flag.String("client", "", "Connect as client to a tcpsh server at <host:port>")
	flagToken  = flag.String("token", "", "Token for -server (hardcode) or -client (authenticate); overrides TCPSH_TOKEN env")
)

func usage() {
	fmt.Fprintf(os.Stderr, "tcpsh — interactive TCP server and connection manager\n\n")
	fmt.Fprintf(os.Stderr, "Modes:\n")
	fmt.Fprintf(os.Stderr, "  Console (default)   Interactive REPL on the local terminal.\n")
	fmt.Fprintf(os.Stderr, "  Server  (-server)   Headless daemon; a client connects over encrypted TCP.\n")
	fmt.Fprintf(os.Stderr, "  Client  (-client)   Connects to a running tcpsh server.\n\n")
	fmt.Fprintf(os.Stderr, "Flags:\n")
	flag.PrintDefaults()
}

// Execute parses flags and runs the selected mode.
func Execute() {
	flag.Usage = usage
	flag.Parse()

	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("config: %w", err)
	}
	if *flagQuiet {
		cfg.Quiet = true
	}

	switch {
	case *flagServer != "":
		srv, err := server.New(cfg, *flagServer, resolveServerToken(*flagToken))
		if err != nil {
			return err
		}
		return srv.Run()

	case *flagClient != "":
		token := resolveToken(*flagToken)
		if token == "" {
			return fmt.Errorf("no token provided — use -token or set TCPSH_TOKEN")
		}
		return client.New(*flagClient, token).Run()

	default:
		repl, err := console.New(cfg)
		if err != nil {
			return err
		}
		if *flagPort > 0 {
			fmt.Printf("Opening port %d...\n", *flagPort)
		}
		return repl.Run()
	}
}

// resolveServerToken returns the token for -server mode.
// Priority: -token flag → TCPSH_TOKEN env → empty (random token generated by server).
func resolveServerToken(flagValue string) string {
	if flagValue != "" {
		return flagValue
	}
	return os.Getenv("TCPSH_TOKEN")
}

// resolveToken returns the token to use for -client mode.
// Priority: -token flag → TCPSH_TOKEN env → interactive prompt.
func resolveToken(flagValue string) string {
	if flagValue != "" {
		return flagValue
	}
	if t := os.Getenv("TCPSH_TOKEN"); t != "" {
		return t
	}
	fmt.Print("Token: ")
	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}
